### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by crackfan** [sgrif/diesel.rs-website#132] opened 2021-08-07 02:08 UTC
docker alpine rust
/app/diesel_demo # cargo -V
cargo 1.54.0 (5ae8d74b3 2021-06-22)
/app/diesel_demo # rustc -V
rustc 1.54.0 (a178d0322 2021-07-26)

/app/diesel_demo # diesel setup
Segmentation fault
/app/diesel_demo # diesel migration generate create_posts
Creating migrations/2021-08-07-020132_create_posts/up.sql
Creating migrations/2021-08-07-020132_create_posts/down.sql

/app/diesel_demo # diesel migration run
Segmentation fault

**Comment by weiznich** [comment] 2021-08-07 08:06
This is the issue tracker for the diesel.rs website, not for diesel itself. That means I will close the issue here.
Feel free to open it at [the diesel issue tracker](https://github.com/diesel-rs/diesel). Be sure to follow the issur template over there + include a backtrace (captured via gdb), as otherwise the issue is not actionable for anyone.

**Closed by weiznich** 2021-08-07 08:06 UTC
