### ISSUE TITLE
Format wast view screen real estate

### ISSUE THREAD

**Issue by gdennie** [sgrif/diesel.rs-website#148] opened 2022-04-06 09:35 UTC
On screens such as [Composing Applications with Diesel](https://diesel.rs/guides/composing-applications.html), the HTML class, `guide-wrapper`, should not have its `width` and `margin-left` CSS properties set to any values. The region should be allowed to fill it container as that already provides sufficient padding. Currently, `guide-wrapper` wast 2/3 of the width, annoyingly clipping the source code examples.

**Comment by weiznich** [comment] 2022-04-06 09:59
Duplicate of #111 and #127

**Closed** 2022-04-06 09:59 UTC
