### ISSUE TITLE
fix: disable site in `http` and do 301 by redirecting it to `https`

### ISSUE THREAD

**Issue by vinayakkulkarni** [sgrif/diesel.rs-website#138] opened 2021-10-06 09:10 UTC
As the title says, this is not a bug or anything, just as suggestion that stop serving the site via `http` & only use `https` for the users to be able to access it.

Thanks.

**Comment by weiznich** [comment] 2021-10-06 09:55
Duplicate of #78

**Closed by weiznich** 2021-10-06 09:55 UTC

**Comment by vinayakkulkarni** [comment] 2021-10-06 16:15
Sorry about this. My bad. Should've searched the issues first.
